### PR TITLE
Support multi-byte string

### PR DESCRIPTION
**Pull request by painnick**
Modified stomp.coffee file to support multi-byte string. And add unit-test code.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Many thanks, I will review your changes.

In addition I will also port the changes to https://github.com/stomp-js/stompjs - next version of this library. You can follow the progress at https://github.com/stomp-js/stompjs/issues/2

**Comment by kum-deepak** [comment]
One interesting observation. The test case passes with the old code as well. Please check.

**Comment by Smiche** [comment]
Alternative PR that has the same result issue #46

**Comment by kum-deepak** [comment]
Closing, in favor of #46

**Comment by kum-deepak** [comment]
Released as version 4.0.8 in NPM

**Pull request closed without merging**
