### PR TITLE
Add closeEventCallback to expose the websocket CloseEvent so that the

### PR DESCRIPTION
**Pull request by dillon-sellars**
I have a use case where I need to access the websocket CloseEvent and do things like `if (closeEvent.code === 1008)...`. This PR adds an closeEventHandler that passes along the CloseEvent from the `@ws.onclose` handler.

### CODE REVIEW

**Comment by kum-deepak** [comment]
Looks all good, I will merge it. Will it be possible to add to docs. If not I will add those.

Many thanks!

**Comment by dillon-sellars** [comment]
Hi Deepak, 

Thanks for the quick response and for keeping this library updated. I'll add something to the docs.

**Comment by kum-deepak** [comment]
One step I have missed in Contribut.md - before committing your next change set, please run `cake build`. It will update generated files (JS, minified JS, HTML docs).

I will update the documentation later.

**Comment by dillon-sellars** [comment]
Updated -- also took a stab at cleaning up `_parseConnect` by handling all the special cases first.

**Comment by kum-deepak** [comment]
Great!

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

**Pull request merged**
