### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Inkata**
more accurate install instructions

### CODE REVIEW

**Comment by kum-deepak** [comment]
Many thanks, will merge it now.

BTW, I was looking for someone who is going to use this library with Node, I need to enable Auto reconnect (which currently is not enabled for Stomp.overTCP). Let me know if you would be interested and will be able to help in testing the changes out.

**Comment by kum-deepak** [comment]
I am not releasing a new version immediately as only README has changed.

**Comment by Inkata** [comment]
I'm starting to use stomp on the browser by way of npm + browserify for provisioning. On the node.js front I think ampqlib fits the bill. My broker is rabbitmq BTW.

**Comment by kum-deepak** [comment]
Great to hear that. I would have imagined so :)

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

**Pull request merged**
