### PR TITLE
Adjusting types to v4

### PR DESCRIPTION
**Pull request by JimiC**
@kum-deepak If you have any questions on the changes, please ask.

### CODE REVIEW

**Comment by kum-deepak** [comment]
@JimiC many thanks for this PR. I have made some additional changes in the header comments. Please see if those are appropriate. After your confirmation, I will merge this PR.

**Comment by JimiC** [comment]
Right. I missed to correct the project URL.

**Comment by kum-deepak** [comment]
Thanks @JimiC and @rockingskier, it is part of 4.0.3 release now available at npm.

**Comment by kum-deepak** [comment]
Planning for next version of stompjs is on the way. Your participation will be really appreciated, please join at https://github.com/stomp-js/stompjs/issues/1

**Pull request merged**
